name: Build

on:
  push:
    branches:
      - 'main'
    tags:
      - 'v*'
    paths:
      - 'src/*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          submodules: recursive
          fetch-depth: 0
      - name: Setup dotnet 7
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.x
      - name: Restore
        run: dotnet restore ./src/
      - name: Build
        run: dotnet build -c Release --no-restore ./src/
      - name: Create nuget package
        run: dotnet pack -c Release ./src/
      - name: Push nuget package
        env:
          NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
        run: |
          dotnet push src/greatalazar.CodeUtils.Lib/bin/Release/greatalazar.CodeUtils.Lib.${{ env.GitVersion_SemVer }}.nupkg \
          --api-key ${{ env.NUGET_API_KEY }} \
          -s https://api.nuget.org/v3/index.json